### ISSUE TITLE
No certificate available

### ISSUE THREAD

**Issue by frost-cqre** [jsiebens/ionscale#13]
Hi,
I am trying Ionscale, but after manual install (not Docker), it fails to provision certificate. Can you please point me to some logs so I can figure out what went wrong?

Thank you

Tomas

**Comment by jsiebens** [comment]
Hi @frost-cqre and @MaxwellSchmidt97 

Unfortunately, no extra logs are configured for the acme provider (yet). 

But can you share your configuration? Because the snippet below is still working for me with release `0.8.2`:

```
server_url: "https://<my domain>"

tls:
  acme: true
  acme_email: "<my email>"
```

Note the `acme: true`. 
The docs were saying `acme_enabled: true` incorrectly and are now updated with the correct property.

Other things the check when using acme:
- make sure ionscale can bind on port 80 and 443
- your server running ionscale is publicly reachable on port 80 and 443
- DNS entries are correctly set and pointing to your server

Hope this helps to get it up and running

**Comment by jsiebens** [comment]
Release v0.9.0 adds additional log support for certmagic, it will hopefully show more information
